CLEAR
EDAD=0
*PROGRAMA PARA INGRESAR EDAD DE UN PACIENTE Y DETERMINAR SI ES MAYOR DE EDAD 
@15,20 SAY "INGRESE EDAD" GET EDAD
READ
IF EDAD > 18 THEN 
@20, 20 SAY "MAYOR DE EDAD"
ELSE
IF EDAD<18 THEN 
@20,20 SAY "MENOR DE EDAD"
 
ENDIF 
ENDIF